site_name: JanusGraph 翻译版(0.3.1)
site_author: FinSightRD


nav:
- Home: index.md
- I.介绍: 
  - 1.JanusGraph优势: ./introduction/the_benefits_of_janusgraph.md
  - 2.架构总览: ./introduction/architectural_overview.md
  - 3.开始: ./introduction/getting_started.md

- II.Janusgraph基础知识:
  - 4.基本配置: ./janusgraph_basics/configuration.md
  - 5.数据实例和数据模型: ./janusgraph_basics/schema_and_data_modeling.md
  - 6.Gremin查询语言: ./janusgraph_basics/gremlin_query_language.md
  - 7.JanusGraph服务端: ./janusgraph_basics/janusgraph_server.md
  - 8.部署方案: ./janusgraph_basics/deployment_scenarios.md
  - 9.配置图工厂: ./janusgraph_basics/configuredgraphfactory.md
  - 10.多节点JanusGraph集群中需要考虑的事项: ./janusgraph_basics/things_to_consider_in_a_multi_node_janusgraph_cluster.md
  - 11.高性能索引: ./janusgraph_basics/indexing_for_better_performance.md
  - 12.事务: ./janusgraph_basics/transactions.md
  - 13.JanusGraph缓存: ./janusgraph_basics/janusgraph_cache.md
  - 14.JanusGraph日志: ./janusgraph_basics/transaction_log.md
  - 15.配置手册: ./janusgraph_basics/configuration_reference.md
  - 16.常见问题: ./janusgraph_basics/common_questions.md
  - 17.技术限制: ./janusgraph_basics/technical_limitations.md

- III.存储后端: 
  - 18.Apache Cassandra: ./storage_backend/apache_cassandra.md
  - 19.Apache Hbase: ./storage_backend/apache_hbase.md


theme: readthedocs
